version: 2.1

# executors:
#   docker-executor:
#     docker:
#       - image: docker:dind-rootless

workflows:
  release:
    jobs:
      - release
  # build:
  #   jobs:
  #     - build


jobs:
  release:
    docker:
      - image: hoppr/semantic-release
    # resource_class: tensorplex/dojo-subnet
    steps:
      - checkout
      - run:
          name: Install Semantic Release plugins
          command: npm install -g -D semantic-release @semantic-release/{git,github,changelog}
      - run:
          name: Run semantic release
          command: npx semantic-release