version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:dind-rootless

workflows:
  release:
    jobs:
      - release
  # build:
  #   jobs:
  #     - build


jobs:
  release:
    docker:
      - image: hoppr/semantic-release
    resource_class: tensorplex/dojo-subnet
    steps:
      - checkout
      - run:
          name: Install Semantic Release plugins and run
          command: |
            npm install -g -D semantic-release @semantic-release/{git,github}
            npx semantic-release
